### ISSUE TITLE
Needs more info about flashing the firmeware

### ISSUE THREAD

**Issue by ad-on-is** [gorbit99/penguin#2]
The documentation says

> Start with the microcontroller, the resistor and the RGBs. This is necessary, because soldering the RGB LEDs can be finicky and you'll want a way to test if you've connected them successfully, which can be done by flashing the microcontroller. 

Could you provide more info on how to do that, especially how to flash the firmware?

I've soldered some of the RGBs and would like to test them before I proceed.

This is what I've done so far (trial & error)

- Copy qmk folder into ~/qmk_firmware/penguin
- qmk compile -kb penguin -km default  
- qmk flash -kb penguin -km default

The documentation of QMK (https://docs.qmk.fm/#/feature_rgb_matrix) says that `rgb_matrix_set_color_all(r, g, b)` can be used to set the color of all LEDs.

So, I added the following at the end of penguin/keymap.c, but the LEDs do not light up.

```
void keyboard_post_init_user(void) {
rgb_matrix_set_color_all(255,255,255);
}
```

I introduced an error in penguin/keymap.c to see whether it throws any erros, but it does not, which seems like qmk is not compling keyboards/penguin/keymaps, but redox/keymaps instead. 

QMK version 1.1.1

**Comment by gorbit99** [comment]
When I was testing it, I wrote a very basic arduino program, that just turned on the leds.
I used this library: https://github.com/Electry/Arduino_SK6812, it has install instructions

and this piece of code:
```c
#include <SK6812.h>

const int numLeds = 35;

SK6812 LED(numLeds);

void setup() {
  LED.set_output(1); // Digital Pin 4
}

int i = 0;

void loop() {
  LED.set_rgbw(i, {0, 0, 255});
  LED.set_rgbw((i - 1 + numLeds) % numLeds, {0, 0, 0});
  LED.sync();
  delay(500);

  i = (i + 1) % numLeds;
}
```
The variable in there should be how many LEDs you already have, and it should go through each one by one. If one of them doesn't do anything, it's soldered on wrong.

**Comment by ad-on-is** [comment]
Thx, I just gave that a try. but with no success. 

An interesting observation I've made was that if I poke around with tweezers and bridge the pin below the kathode with that of another led, some of the leds light up, so I assume the soldering should be fine. 

I also poked around at the diode/switch pins to see whether the keys work, and they do.

**Comment by gorbit99** [comment]
If you upload a picture, I can check what's wrong. The script and the pcb should be fine, so either the leds are of the wrong make, or the soldering isn't perfect

**Comment by ad-on-is** [comment]
Thx... I found the cause. I did not hook up a resistor. Since I don't have 680 ohms, I tried a 570 ohm, and a chained 570 + 200 ohm ~ 780ohm resistor, but only the first LED blinks up.

Do I need exactly 680 ohms?

**Comment by gorbit99** [comment]
No, the resistor is pretty much for safety reasons, 570 ohm should be fine. You probably have a faulty connection between led 1 and 2

**Comment by ad-on-is** [comment]
Ok, good to know. I also tried it on a fresh board, and just placed the leds on the pcb holding them down with my finger... It's the same result.

**Comment by ad-on-is** [comment]
btw: the pics:

https://photos.app.goo.gl/XYUpSic2wgAKzSK96
https://photos.app.goo.gl/aQgdYDMbeMGR8T9m7

Not an expert in soldering, but looks fine to me

**Comment by ad-on-is** [comment]
Nevermind, turned out I did a terrible soldering job the first time. Didn't apply pre-solder to the led pins... Thankfully I had a heatgun to unsolder them and redid everything on a new board.

They're shining like stars now :-D
https://photos.app.goo.gl/79waq9Esb4HWKdkC7

**Comment by gorbit99** [comment]
Oh, that's great to hear, good luck on the rest of the build as well then, I'll close this issue
